import "@/node_modules/react-modal-video/css/modal-video.css";
import "public/assets/css/style.css";
import "public/assets/css/responsive.css";
import "swiper/css";
// import "swiper/css/navigation"
import "swiper/css/pagination";
import "swiper/css/free-mode";
import { niconne, poppins, tangerine } from "@/lib/font";
import Head from "next/head";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Алайку",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "700"] });

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${niconne.variable} ${inter.className} ${poppins.variable} ${tangerine.variable}`}
    >
      <Head></Head>
      <body>{children}</body>
    </html>
  );
}
